server:
  port: ${SERVER_PORT:8080}

spring:
  profiles:
    active: ${ENV:dev}

  servlet:
    multipart:
      max-file-size: 1MB

  mail:

    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

host_url: ${VERIFY_EMAIL_HOST}