spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

SERVER_PORT: 8080

#EMAIL CONFIG
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: nadeempalkhiwala9@gmail.com
EMAIL_PASSWORD: akxotpqucexvsflw
VERIFY_EMAIL_HOST: https://vaistra-management-system.up.railway.app
