spring:
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/vaistra-management-system
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

SERVER_PORT: 8080

#EMAIL CONFIG
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: nadeempalkhiwala9@gmail.com
EMAIL_PASSWORD: akxotpqucexvsflw
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}