spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vaistra-management-system
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update

SERVER_PORT: 8082

#EMAIL CONFIG
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: nadeempalkhiwala9@gmail.com
EMAIL_PASSWORD: akxotpqucexvsflw
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}