spring:
  datasource:
    url: jdbc:postgresql://dpg-ck1vdcfhdsdc73d0722g-a.oregon-postgres.render.com:5432/vaistradb
    username: vaistradb_user
    password: AehoiOTYFsxexqqGHTOKm0j2Yrtrg4Pm
  jpa:
    hibernate:
      ddl-auto: update

SERVER_PORT: 8080

#EMAIL CONFIG
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: nadeempalkhiwala9@gmail.com
EMAIL_PASSWORD: akxotpqucexvsflw
VERIFY_EMAIL_HOST: https://vaistra-management-system.up.railway.app
